// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC93RF7U0dtvo8MOHxgpDPP6bHML6Jz6S4',
    appId: '1:98039447169:web:a5de21bf9ecd44bfa51780',
    messagingSenderId: '98039447169',
    projectId: 'health-record-ocr-dev',
    authDomain: 'health-record-ocr-dev.firebaseapp.com',
    storageBucket: 'health-record-ocr-dev.firebasestorage.app',
    measurementId: 'G-2QW60FJ27J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNfgl3TjX25ECFgl4dA-iDqmixGwaWlN4',
    appId: '1:98039447169:android:1cfb0615f963e191a51780',
    messagingSenderId: '98039447169',
    projectId: 'health-record-ocr-dev',
    storageBucket: 'health-record-ocr-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCed7wL7V-SomWHKoIQM50lQq8A2i80xZA',
    appId: '1:98039447169:ios:76e947afef3283b6a51780',
    messagingSenderId: '98039447169',
    projectId: 'health-record-ocr-dev',
    storageBucket: 'health-record-ocr-dev.firebasestorage.app',
    iosBundleId: 'com.infinitiv.ai.healthRecordOcrModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCed7wL7V-SomWHKoIQM50lQq8A2i80xZA',
    appId: '1:98039447169:ios:76e947afef3283b6a51780',
    messagingSenderId: '98039447169',
    projectId: 'health-record-ocr-dev',
    storageBucket: 'health-record-ocr-dev.firebasestorage.app',
    iosBundleId: 'com.infinitiv.ai.healthRecordOcrModule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC93RF7U0dtvo8MOHxgpDPP6bHML6Jz6S4',
    appId: '1:98039447169:web:29ddd3f4c4d5ce94a51780',
    messagingSenderId: '98039447169',
    projectId: 'health-record-ocr-dev',
    authDomain: 'health-record-ocr-dev.firebaseapp.com',
    storageBucket: 'health-record-ocr-dev.firebasestorage.app',
    measurementId: 'G-01X5BD7293',
  );
}
